import sonicGuiImage from '../assets/images/projects/sonic-gui.png';
import chessImage from '../assets/images/projects/oop-chess.png';
import bubbleImage from '../assets/images/projects/bubble.png';
import fosImage from '../assets/images/projects/fos.png';

const baseColors = {
  primaryColor: '#818cf8',
  secondaryColor: '#818cf8',
  textOnPrimary: '#ffffff',
  textOnSecondary: '#ffffff',
  background: '#18181b',
  cardBackground: '#27272a',
  cardBorder: '#818cf8',
};

export const loadProject = async (slug) => {
  const projects = {
    trustflow: {
      slug: 'trustflow',
      title: 'TrustFlow',
      description: 'Live — a co-owned product I help build end to end with the project’s other founder.',
      longDescription: 'TrustFlow is a live product I co-own with the project’s other founder. My contribution spans product development, full-stack implementation, and UI/UX work, with merged pull requests to date, primarily UI/UX.',
      technologies: ['Product Development', 'Full-Stack Development', 'UI/UX'],
      github: 'https://github.com/abyssrift/TrustFlow',
      features: [
        '64 merged pull requests, primarily UI/UX',
        'End-to-end product development',
        'Full-stack implementation',
        'co-ownership with the project’s other founder',
      ],
      ...baseColors,
    },
    'local-rag-system': {
      slug: 'local-rag-system',
      title: 'Local RAG System',
      description: 'Done — a containerized retrieval-augmented generation system for local document querying.',
      longDescription: 'A completed local RAG system for ingesting PDF and DOCX files and answering natural-language questions. The pipeline handles document parsing, chunking, embeddings, vector retrieval with ChromaDB, and locally generated answers through Ollama, exposed through a FastAPI query API and packaged with Docker.',
      technologies: ['FastAPI', 'ChromaDB', 'Ollama', 'Docker'],
      github: 'https://github.com/lleoparden/RAG-NLP-project',
      features: [
        'PDF and DOCX document ingestion',
        'Chunking, embeddings, and vector retrieval',
        'Local answer generation with Ollama',
        'FastAPI query interface',
        'Dockerized local deployment',
      ],
      ...baseColors,
    },
    olympus: {
      slug: 'olympus',
      title: 'Olympus',
      description: 'Ongoing — currently paused and expected to resume.',
      longDescription: 'Olympus is an ongoing self-hosted local AI stack integrating Hermes, Odysseus, and Jarvis behind a native orchestration layer. It is designed around local, single-GPU model workflows. Development is currently paused, with work expected to resume.',
      technologies: ['Python', 'JavaScript', 'Ollama', 'Docker'],
      github: 'https://github.com/lleoparden/olympus',
      features: [
        'Self-hosted local AI workflow',
        'Native orchestration layer',
        'Integration work across Hermes, Odysseus, and Jarvis',
        'Single-GPU local model focus',
      ],
      ...baseColors,
    },
    sentinelcheck: {
      slug: 'sentinelcheck',
      title: 'SentinelCheck',
      description: 'Planned — a graduation capstone concept at the planning stage, not a built product.',
      longDescription: 'SentinelCheck is a planned graduation capstone concept for a team of six. The proposed anti-scam app would detect potential fraud across QR codes, SMS and WhatsApp messages, calls, and payment screenshots, with Egyptian Arabic and Arabizi scam-language analysis as a planned differentiator. It remains at the concept stage and has not been built yet.',
      technologies: ['React Native', 'Supabase', 'Hugging Face Spaces'],
      features: [
        'Planned QR-code scam detection',
        'Planned message, call, and payment-screenshot analysis',
        'Planned Egyptian Arabic and Arabizi scam-language support',
      ],
      ...baseColors,
    },
    'job-tracker': {
      slug: 'job-tracker',
      title: 'Job Application Tracking System',
      description: 'In progress — a multi-platform system for tracking and managing job applications.',
      longDescription: 'An in-progress job application tracker spanning web, mobile, and browser-extension clients on a unified FastAPI backend with Firebase Auth and Firestore. The planned workflow includes centralized status tracking, filtering and analytics, CSV and JSON import/export, and Gmail-based status automation that is still in progress.',
      technologies: ['React Native', 'FastAPI', 'Firebase'],
      github: 'https://github.com/lleoparden/job-tracker',
      features: [
        'Web, mobile, and browser-extension clients',
        'Unified FastAPI backend',
        'Firebase authentication and Firestore data',
        'Status filtering and analytics',
        'CSV and JSON import/export',
      ],
      ...baseColors,
    },
    'kotlin-chat-application': {
      slug: 'kotlin-chat-application',
      title: 'Kotlin Chat Application',
      description: 'Done — an Android chat application with local persistence and optional Firebase sync.',
      longDescription: 'A completed Kotlin Android chat application with local persistence and optional Firebase synchronization. It supports group chats, stories, media uploads, voice messages, theming, and offline use.',
      technologies: ['Kotlin', 'Android', 'Firebase'],
      github: 'https://github.com/lleoparden/Chat_Application',
      image: bubbleImage,
      features: [
        'Group chats and stories',
        'Media uploads and voice messages',
        'Local persistence and optional Firebase sync',
        'Theming and offline support',
      ],
      ...baseColors,
    },
    'oop-chess': {
      slug: 'oop-chess',
      title: 'OOP Chess',
      description: 'Done — an object-oriented Java chess game with a graphical interface and chaos mode.',
      longDescription: 'A completed object-oriented chess implementation in Java with a graphical interface, standard play, an alternate chaos mode, move validation, and a bot based on minimax with alpha-beta pruning.',
      technologies: ['Java', 'JavaFX', 'Object-Oriented Programming'],
      github: 'https://github.com/lleoparden/oop-chess',
      image: chessImage,
      features: [
        'Standard and chaos-mode gameplay',
        'Graphical interface and move validation',
        'Object-oriented game architecture',
        'Minimax bot with alpha-beta pruning',
      ],
      ...baseColors,
    },
    'sonic-gui': {
      slug: 'sonic-gui',
      title: 'SONiC-GUI',
      description: 'Done — an AI-assisted network-management platform for SONiC OS.',
      longDescription: 'A completed full-stack network administration platform for SONiC OS with real-time device monitoring and VLAN and port management. Its FastAPI backend uses secure SSH communication and JWT authentication, while an experimental Gemini and LangChain integration translates natural-language requests into validated network actions. No repository link is shown because an accurate repository has not been confirmed.',
      technologies: ['React', 'FastAPI', 'Redis', 'WebSockets', 'Gemini API', 'LangChain'],
      image: sonicGuiImage,
      features: [
        'Real-time device monitoring',
        'VLAN and port management',
        'Secure SSH communication and JWT authentication',
        'AI-assisted natural-language network actions',
        'Docker and GitHub Actions workflow',
      ],
      ...baseColors,
    },
    'fos-educational-os': {
      slug: 'fos-educational-os',
      title: 'FOS Educational OS',
      description: 'Done — educational x86 kernel development in C.',
      longDescription: 'A completed educational operating-system project in C targeting x86. The work covers kernel memory management, page-fault handling, scheduling, synchronization, system calls, and kernel-to-user isolation within the FOS framework.',
      technologies: ['C', 'x86', 'Virtual Memory', 'Scheduling'],
      github: 'https://github.com/lleoparden/FOS_TEMPLATE',
      image: fosImage,
      features: [
        'Kernel and user-space memory management',
        'Page-fault and trap handling',
        'Scheduling and synchronization primitives',
        'System-call interface and privilege isolation',
      ],
      ...baseColors,
    },
    odysseus: {
      slug: 'odysseus',
      title: 'Odysseus — Selected Open-Source Contributions',
      description: 'Merged contributions to someone else’s open-source AI workspace; not a project I own.',
      longDescription: 'Selected contributions to Odysseus, PewDiePie’s open-source AI workspace. The work includes merged pull requests, such as adding ArrowUp recall for the last message and fixing a Brain/Cookbook drag issue traced to an ES module root cause. I have also applied for a maintainer role. Odysseus is not my project and is presented here only as open-source contribution work.',
      technologies: ['Python', 'Open Source'],
      github: 'https://github.com/arcahyadi/odysseus',
      features: [
        'Merged open-source pull requests',
        'ArrowUp recall for the last message',
        'Brain/Cookbook drag bug investigation and fix',
        'Maintainer-role application',
      ],
      ...baseColors,
    },
  };

  return projects[slug] || null;
};

export const loadAllProjects = () => [
  {
    slug: 'trustflow',
    title: 'TrustFlow',
    status: 'Live',
    description: 'Live — co-owned product with merged PRs, spanning product, full-stack, and UI/UX work.',
    technologies: ['Product Development', 'Full-Stack Development', 'UI/UX'],
    github: 'https://github.com/abyssrift/TrustFlow',
  },
  {
    slug: 'local-rag-system',
    title: 'Local RAG System',
    status: 'Completed',
    description: 'Done — containerized local document ingestion, retrieval, and question answering.',
    technologies: ['FastAPI', 'ChromaDB', 'Ollama', 'Docker'],
    github: 'https://github.com/lleoparden/RAG-NLP-project',
  },
  {
    slug: 'olympus',
    ongoing: true,
    title: 'Olympus',
    status: 'Ongoing · paused',
    description: 'Ongoing — currently paused and expected to resume; a self-hosted local AI stack for single-GPU workflows.',
    technologies: ['Python', 'JavaScript', 'Ollama', 'Docker'],
    github: 'https://github.com/lleoparden/olympus',
  },
  {
    slug: 'sentinelcheck',
    title: 'SentinelCheck',
    status: 'Planned',
    description: 'Planned — a graduation capstone concept at the planning stage, not a built product.',
    technologies: ['React Native', 'Supabase'],
  },
  {
    slug: 'job-tracker',
    title: 'Job Application Tracking System',
    status: 'In progress',
    description: 'In progress — a multi-platform tracker with a FastAPI backend and Firebase.',
    technologies: ['React Native', 'FastAPI', 'Firebase'],
    github: 'https://github.com/lleoparden/job-tracker',
  },
  {
    slug: 'kotlin-chat-application',
    title: 'Kotlin Chat Application',
    status: 'Completed',
    description: 'Done — an Android chat app with local persistence, optional Firebase sync, and offline support.',
    technologies: ['Kotlin', 'Android', 'Firebase'],
    image: bubbleImage,
    github: 'https://github.com/lleoparden/Chat_Application',
  },
  {
    slug: 'oop-chess',
    title: 'OOP Chess',
    status: 'Completed',
    description: 'Done — an object-oriented Java chess game with a graphical interface and chaos mode.',
    technologies: ['Java', 'JavaFX'],
    image: chessImage,
    github: 'https://github.com/lleoparden/oop-chess',
  },
  {
    slug: 'sonic-gui',
    title: 'SONiC-GUI',
    status: 'Completed',
    description: 'Done — an AI-assisted network-management platform for SONiC OS.',
    technologies: ['React', 'FastAPI', 'Redis', 'WebSockets'],
    image: sonicGuiImage,
  },
  {
    slug: 'fos-educational-os',
    title: 'FOS Educational OS',
    status: 'Completed',
    description: 'Done — educational x86 kernel development covering memory, faults, scheduling, and isolation.',
    technologies: ['C', 'x86', 'Virtual Memory'],
    image: fosImage,
    github: 'https://github.com/lleoparden/FOS_TEMPLATE',
  },
  {
    slug: 'odysseus',
    title: 'Odysseus — Open-Source Contributions',
    status: 'Contribution',
    description: 'Selected merged contributions to someone else’s open-source AI workspace; not a project I own.',
    technologies: ['Python', 'Open Source'],
    github: 'https://github.com/arcahyadi/odysseus',
  },
];

export const loadSmallProjects = () => [];
